### ISSUE TITLE
about data_X.npy and data_Y.npy

### ISSUE THREAD

**Issue by cdliang11** [sajabdoli/UAP#1]
X=np.load(os.path.join(dir_of_file,"data","data_X.npy"))
Y=np.load(os.path.join(dir_of_file,"data","data_Y.npy"))

what are data_X.npy and data_Y.npy?

**Comment by sajabdoli** [comment]
These are the input audio and one-hot labels matrices.  Please download the audio files from
[https://urbansounddataset.weebly.com/urbansound8k.html](https://urbansounddataset.weebly.com/urbansound8k.html)
